#!/bin/bash

if [[ $OSTYPE == darwin* ]]; then
    dir=$(dirname $0)
    path=$PWD${dir:1}
else
    path=$(dirname $(readlink -f $0))
fi

mkdir -p ~/.bash_plugins
ln -s "$path"/weather ~/.bash_plugins/weather
